apiVersion: v1
kind: Pod
metadata:
  name: machine-learning-cuda
  namespace: group-mlops
spec:
  containers:
    - name: cuda-container
      image: harbor.centralretail.com.vn/group_platform/nvidia-cuda:12.1.0
      imagePullPolicy: Always
      command: ["/bin/bash", "-c", "sleep infinity"]
      tty: true
      stdin: true
      resources:
        limits:
          nvidia.com/gpu: 1
        requests:
          nvidia.com/gpu: 1
          memory: "4Gi"   
          cpu: "4" 
      securityContext:
        runAsUser: 0
  imagePullSecrets:
    - name: harbor-registry-secret