image: harbor.cxview.local/cxviewpublic/gitlab-runner:1.0.0

stages:
  - build

variables:
  DOCKER_DRIVER: overlay2
  CI_REGISTRY: harbor.cxview.local
  CONTAINER_IMAGE: $CI_REGISTRY/cxview/ds-core
  CONTAINER_IMAGE_BASE: $CI_REGISTRY/cxview/deepstream-people
  GIT_SUBMODULE_STRATEGY: normal

.before_script_template: &before_script
  - echo "Hello cxview core people counting!"
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

# Build x86
buildimage-x86:
  stage: build
  rules:
    - if: '$CI_COMMIT_TAG =~ /^release/'
  before_script:
    *before_script
  script:
    - |
      VERSION="${CI_COMMIT_TAG#release/v}"
      echo "Tag GitLab: $CI_COMMIT_TAG"
      echo "Docker Image Version: $VERSION"
    - echo "Building x86 image ..."
    - docker build --pull -t $CONTAINER_IMAGE_BASE:0.1-base-x86 -f deploy/Dockerfile.base.x86 .
    - docker push $CONTAINER_IMAGE_BASE:0.1-base-x86
    - docker build --pull -t $CONTAINER_IMAGE:$VERSION-base-x86 -f deploy/Dockerfile.x86 .
    - docker push $CONTAINER_IMAGE:$VERSION-base-x86
  tags:
    - k8s-runner-gpu