image: harbor.cxview.local/cxviewpublic/gitlab-runner:1.0.0

stages:
  - build

variables:
  DOCKER_DRIVER: overlay2
  CI_REGISTRY: harbor.cxview.local
  CONTAINER_IMAGE: $CI_REGISTRY/cxview/cxview-plugin
  GIT_SUBMODULE_STRATEGY: recursive

.before_script_template: &before_script
  - echo "Hello cxview plugin for people couting edge box!"
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

# Build x86
buildimage-x86:
  stage: build
  rules:
    - if: '$CI_COMMIT_TAG =~ /^release/'
  before_script:
    *before_script
  script:
    - |
      VERSION="${CI_COMMIT_TAG#release/v}"
      echo "Tag GitLab: $CI_COMMIT_TAG"
      echo "Docker Image Version: $VERSION"
    - echo "Building x86 image ..."
    - docker build --pull -t $CONTAINER_IMAGE:$VERSION-base-x86 -f docker/Dockerfile.x86 .
    - docker push $CONTAINER_IMAGE:$VERSION-base-x86
  tags:
    - k8s-prod